language: objective-c
osx_image: xcode9
notifications:
  email: 
    - hsoi@hsoienterprises.com
script:
    - xcodebuild -project HELargeCenterTabBarController.xcodeproj -scheme HELargeCenterTabBarController -sdk iphonesimulator11.0 build
