language: objective-c
osx_image: xcode7.3
notifications:
  email: 
    - hsoi@hsoienterprises.com
script:
    - xcodebuild -project HELargeCenterTabBarController.xcodeproj -scheme HELargeCenterTabBarController -sdk iphonesimulator9.3 build
